services:
  base-core-app:
    container_name: base-core
    image: base-core
    platform: linux/amd64
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - '8000:8000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
